## D01 WORKSHOP

**문제 0**
- 1월부터 12월까지 다음과 같은 형태로 달력이 출력되도록 코드를 작성하세요.
```bash
1 월
일 월 화 수 목 금 토
1 2 3 4 5 6 7
8 9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30 31
2 월
일 월 화 수 목 금 토
1 2 3 4 5 6 7
8 9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
```

In [74]:
#정답

mon_count = {1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
#print(mon_count)

indent_count = 0

for i in mon_count:
    print(f"{i} 월")
    print("일\t월\t화\t수\t목\t금\t토")
    for j in range(1,mon_count[i]+1):
        if j%7 == 0:
            print(j)
            continue
            
    print(j,end="\t")
    print()

1 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
2 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28

3 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
4 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30
5 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
6 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30
7 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
8 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
9 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30
10 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
11 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30
12 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31

In [95]:
#정답

mon_count = {1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
#print(mon_count)

pivot = 0

for i in mon_count:
    print(f"{i} 월")
    print("일\t월\t화\t수\t목\t금\t토")
    
      
    print("\t"*pivot,end="")
    for j in range(1, mon_count[i]+1):
        
        if (j+pivot)%7 == 0:  # 3칸이 밀렸으니까 나누기 할 때 4+3 해야함. (2월기준, pivot=3)
            
            if(j == mon_count[i]):
                print(j,end="")
                break
            
            print(j)
            continue
            
        print(j,end="\t")
    pivot = (mon_count[i]+pivot)%7
    print("\n")

1 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31

2 월
일	월	화	수	목	금	토
			1	2	3	4
5	6	7	8	9	10	11
12	13	14	15	16	17	18
19	20	21	22	23	24	25
26	27	28

3 월
일	월	화	수	목	금	토
			1	2	3	4
5	6	7	8	9	10	11
12	13	14	15	16	17	18
19	20	21	22	23	24	25
26	27	28	29	30	31

4 월
일	월	화	수	목	금	토
						1
2	3	4	5	6	7	8
9	10	11	12	13	14	15
16	17	18	19	20	21	22
23	24	25	26	27	28	29
30

5 월
일	월	화	수	목	금	토
	1	2	3	4	5	6
7	8	9	10	11	12	13
14	15	16	17	18	19	20
21	22	23	24	25	26	27
28	29	30	31

6 월
일	월	화	수	목	금	토
				1	2	3
4	5	6	7	8	9	10
11	12	13	14	15	16	17
18	19	20	21	22	23	24
25	26	27	28	29	30

7 월
일	월	화	수	목	금	토
						1
2	3	4	5	6	7	8
9	10	11	12	13	14	15
16	17	18	19	20	21	22
23	24	25	26	27	28	29
30	31

8 월
일	월	화	수	목	금	토
		1	2	3	4	5
6	7	8	9	10	11	12
13	14	15	16	17	18	19
20	21	22	23	24	25	26
27	28	29	30	31

9 월
일	월	화	수	목	금	토
					1	2
3	4	5	6	7	8	9
10	11	12	13	14	15	16
17	18	19	20	21	22	23
24	25	26	27	28	29	30

10 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31

11 월
일	월	화	수	목	금	토
			1	2	3	4
5	6	7	8	9	10	11
12	13	14	15	16	17	18
19	20	21	22	23	24	25
26	27	28	29	30

12 월
일	월	화	수	목	금	토
					1	2
3	4	5	6	7	8	9
10	11	12	13	14	15	16
17	18	19	20	21	22	23
24	25	26	27	28	29	30
31

In [22]:
# 정답


for i in range(1,13):
    print(f"{i} 월")
    print("일\t월\t화\t수\t목\t금\t토")
    
    if i == 2:
        for j in range(1,29):
            if j%7 == 1:
                for k in range(j,j+7):
                    if k == 29:
                        break
                    print(k, end = "\t")
                print()    
    
    elif i == 1 or i ==3 or i ==5 or i ==7 or i ==8 or i ==10 or i ==12:
        for j in range(1,32):
            if j%7 == 1:
                for k in range(j,j+7):
                    if k == 32:
                        break
                    print(k, end = "\t")
                print() 
               
    else:
        for j in range(1,31):
            if j%7 == 1:
                for k in range(j,j+7):
                    if k == 31:
                        break
                    print(k, end = "\t")
                print()

1 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
2 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
3 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
4 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30
5 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
6 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30
7 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
8 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
9 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30
10 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31
11 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30
12 월
일	월	화	수	목	금	토
1	2	3	4	5	6	7
8	9	10	11	12	13	14
15	16	17	18	19	20	21
22	23	24	25	26	27	28
29	30	31

In [11]:
j=1
for k in (j,j+7):
    print(k, end = " ")

1 8

**문제 1**
- 두 개의 정수 n과 m이 주어집니다. 반복문을 사용하지 않고 별(*) 문자를 이용해 가로의 길이가 n, 세로의 길이가 m인 직사각형 형태를 출력해보세요.

In [91]:
# 문제
n = 5
m = 9
# 정답
star = '*'

print((f"{star}"*n + "\n")*m)


print("",end="\n\n")


print(("*"*n + "\n")*m)

*****
*****
*****
*****
*****
*****
*****
*****
*****



*****
*****
*****
*****
*****
*****
*****
*****
*****

**문제2**
- 다음 딕셔너리에서 평균 점수를 출력하시오.

In [56]:
# 문제
student = {'python': 80, 'algorithm': 99, 'django': 89, 'flask': 83}
# 정답

print(sum(student.values())/len(student))

87.75

**문제3**
- 다음은 학생들의 혈액형(A, B, AB, O)에 대한 데이터이다. for문을 이용하여 각 혈액형 별 학생수의 합계를 구하시오.

In [1]:
# 문제
blood_types = ['A', 'B', 'A', 'O', 'AB', 'AB', 'O', 'A', 'B', 'O', 'B', 'AB']
# 정답

# blood={'A':0,'B':0,'AB':0,'O':0}
# for i in blood_types:
#     if i =='A':
#         blood['A'] += 1
#     if i =='B':
#         blood['B'] += 1
#     if i =='AB':
#         blood['AB'] += 1
#     if i =='O':
#         blood['O'] += 1
    
# print(blood)    
    
blood={'A':0,'B':0,'AB':0,'O':0}
for i in blood_types:
    blood[i]+=1
    
print(blood)

{'A': 3, 'B': 3, 'AB': 3, 'O': 3}

In [101]:
blood_types = ['A', 'B', 'A', 'O', 'AB', 'AB', 'O', 'A', 'B', 'O', 'B', 'AB']
result={}
for i in blood_types:
    
    if i in result:
        result[i]+=1
    else:
        result[i] = 1
print(result)

{'A': 3, 'B': 3, 'O': 3, 'AB': 3}